import os

# Define the niches and their replacements
niches = [
    {
        "file": "hvac.html",
        "url": "hvac",
        "title": "HVAC Landing Pages | Custom Pages That Book Installs | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for HVAC contractors. Get more AC install leads, heater repair calls, and booked service appointments with a page engineered for your market.",
        "og_title": "HVAC Landing Pages That Book Installs | Naslogic",
        "og_desc": "Custom-built landing pages for HVAC contractors. More leads, more booked installs, zero wasted ad spend.",
        "schema_name": "HVAC Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for HVAC contractors. Our pages are designed to convert visitors into booked estimates for services like AC installation, furnace repair, and routine maintenance.",
        "schema_service": "Landing Page Design for HVAC Contractors",
        "faq1": "Our HVAC landing pages start at $199 for a single high-converting page with mobile-first design, SEO optimization, and conversion-focused layouts.",
        "faq2_q": "Why do HVAC contractors need a dedicated landing page?",
        "faq2_a": "HVAC companies spend significant budgets driving traffic, but most send visitors to generic homepages. A dedicated landing page with a single call-to-action can increase conversion rates by 2x to 5x compared to a standard website.",
        "faq3_q": "How fast can Naslogic deliver an HVAC landing page?",
        "faq3_a": "We deliver production-ready HVAC landing pages on rapid turnarounds. Most single-page projects are completed within days.",
        "faq4_a": "Absolutely. Over 70% of homeowners searching for emergency AC or heater repair do so on their phone. Our pages are engineered to load fast and capture mobile leads.",
        "faq5_a": "Yes. We integrate with popular HVAC CRMs like ServiceTitan and Housecall Pro, as well as general tools like HubSpot and Calendly.",
        "h1_2": "For HVAC",
        "h1_3": "Contractors",
        "hook": "Naslogic builds high-converting landing pages exclusively for HVAC contractors. We design pages that turn website visitors into booked service calls for AC replacements, furnace repairs, and tune-ups. No generic templates. Every page is custom-engineered to match your HVAC market and generate qualified leads on autopilot.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See HVAC Examples",
        "prob_h2": "Why Most HVAC Websites Fail",
        "prob_sub": "HVAC contractors invest in marketing, but their websites let them down. Homeowners sweating with a broken AC or freezing with a dead furnace need to trust you instantly — or they bounce to the next contractor.",
        "prob1_p": "You get clicks from homeowners searching for emergency AC repair, but your site does not give them a clear next step. They leave without ever booking a call.",
        "prob2_p": "Over 70% of homeowners search for HVAC services on their phone. If your site loads slowly, you are losing high-ticket install leads every single day.",
        "prob3_p": "Template websites make HVAC companies look like every other contractor in town. Homeowners cannot tell you apart from the competition.",
        "comp_sub": "See why HVAC contractors choose a specialist over a one-size-fits-all agency.",
        "comp_1": "HVAC industry expertise",
        "comp_1_check": "Built for HVAC contractors",
        "comp_crm": "ServiceTitan, Housecall Pro",
        "port_h2": "HVAC Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for HVAC companies to turn visitors into scheduled service calls and signed contracts.",
        "port_1_img": "HVAC LP Preview",
        "port_1_title": "Emergency AC Repair Experts",
        "port_1_t1": "Residential HVAC",
        "port_1_t2": "Lead Gen",
        "port_1_t3": "Service Booking",
        "port_2_img": "Commercial HVAC LP",
        "port_2_title": "Commercial HVAC Specialists",
        "port_2_t1": "Commercial",
        "port_2_t2": "Rooftop Units",
        "port_2_t3": "B2B Leads",
        "step_1": "We learn your HVAC niche — residential installs, emergency repair, commercial maintenance — and map out your ideal customer journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to HVAC marketing best practices.",
        "step_3": "Your page goes live and starts converting visitors into booked service calls, free estimates, and signed contracts.",
        "faq_sub": "Common questions from HVAC contractors about our landing page design and lead generation services.",
        "cta_h2": "Ready to Book More HVAC Jobs?",
        "cta_p": "Stop losing homeowners to competitors with better websites. Get a landing page that converts AC and heating searches into signed tickets."
    },
    {
        "file": "plumbing.html",
        "url": "plumbing",
        "title": "Plumbing Landing Pages | Custom Pages That Book Calls | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for plumbing contractors. Get more leak repair leads, water heater installs, and booked service calls with a page engineered for your market.",
        "og_title": "Plumbing Landing Pages That Book Calls | Naslogic",
        "og_desc": "Custom-built landing pages for plumbing contractors. More leads, more booked calls, zero wasted ad spend.",
        "schema_name": "Plumbing Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for plumbing contractors. Our pages are designed to convert visitors into booked estimates for services like leak repair, water heater installation, and repiping.",
        "schema_service": "Landing Page Design for Plumbing Contractors",
        "faq1": "Our plumbing landing pages start at $199 for a single high-converting page with mobile-first design, SEO optimization, and conversion-focused layouts.",
        "faq2_q": "Why do plumbers need a dedicated landing page?",
        "faq2_a": "Plumbers spend significant budgets driving traffic, but most send visitors to generic homepages. A dedicated landing page with a single call-to-action can increase conversion rates by 2x to 5x compared to a standard website.",
        "faq3_q": "How fast can Naslogic deliver a plumbing landing page?",
        "faq3_a": "We deliver production-ready plumbing landing pages on rapid turnarounds. Most single-page projects are completed within days.",
        "faq4_a": "Absolutely. Over 75% of homeowners searching for an emergency plumber do so on their phone. Our pages are engineered to load fast and capture mobile leads.",
        "faq5_a": "Yes. We integrate with popular CRMs like ServiceTitan and Housecall Pro, as well as general tools like HubSpot and Calendly.",
        "h1_2": "For Plumbing",
        "h1_3": "Contractors",
        "hook": "Naslogic builds high-converting landing pages exclusively for plumbing contractors. We design pages that turn website visitors into booked service calls for leak repairs, water heater installs, and repiping. No generic templates. Every page is custom-engineered to match your plumbing market and generate qualified leads on autopilot.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Plumbing Examples",
        "prob_h2": "Why Most Plumbing Websites Fail",
        "prob_sub": "Plumbers invest in marketing, but their websites let them down. Homeowners with a burst pipe or broken water heater need to trust you instantly — or they bounce to the next contractor.",
        "prob1_p": "You get clicks from homeowners searching for emergency plumbers, but your site does not give them a clear next step. They leave without ever booking a call.",
        "prob2_p": "Over 75% of homeowners search for plumbers on their phone. If your site loads slowly, you are losing high-ticket install leads every single day.",
        "prob3_p": "Template websites make plumbing companies look like every other contractor in town. Homeowners cannot tell you apart from the competition.",
        "comp_sub": "See why plumbers choose a specialist over a one-size-fits-all agency.",
        "comp_1": "Plumbing industry expertise",
        "comp_1_check": "Built for plumbers",
        "comp_crm": "ServiceTitan, Housecall Pro",
        "port_h2": "Plumbing Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for plumbing companies to turn visitors into scheduled service calls and signed contracts.",
        "port_1_img": "Plumbing LP Preview",
        "port_1_title": "24/7 Emergency Plumbers",
        "port_1_t1": "Residential Plumbing",
        "port_1_t2": "Lead Gen",
        "port_1_t3": "Emergency Service",
        "port_2_img": "Commercial Plumbing LP",
        "port_2_title": "Commercial Pipe & Drain",
        "port_2_t1": "Commercial",
        "port_2_t2": "Hydro Jetting",
        "port_2_t3": "B2B Leads",
        "step_1": "We learn your plumbing niche — residential repair, water heaters, commercial repiping — and map out your ideal customer journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to plumbing marketing best practices.",
        "step_3": "Your page goes live and starts converting visitors into booked service calls, free estimates, and signed contracts.",
        "faq_sub": "Common questions from plumbing contractors about our landing page design and lead generation services.",
        "cta_h2": "Ready to Book More Plumbing Jobs?",
        "cta_p": "Stop losing homeowners to competitors with better websites. Get a landing page that converts emergency searches into signed tickets."
    },
    {
        "file": "dental.html",
        "url": "dental",
        "title": "Dental Landing Pages | Custom Pages That Book Patients | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for dental practices. Get more implant leads, Invisalign patients, and booked appointments.",
        "og_title": "Dental Landing Pages That Book Patients | Naslogic",
        "og_desc": "Custom-built landing pages for dentists. More new patients, more high-ticket cases, zero wasted ad spend.",
        "schema_name": "Dental Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for dental practices. Our pages are designed to convert visitors into booked appointments for services like implants, clear aligners, and cosmetic dentistry.",
        "schema_service": "Landing Page Design for Dental Practices",
        "faq1": "Our dental landing pages start at $199 for a single high-converting page with mobile-first design and SEO optimization.",
        "faq2_q": "Why do dentists need a dedicated landing page?",
        "faq2_a": "Dental practices spend big on Google Ads, but most send visitors to generic homepages. A dedicated landing page can increase patient conversion rates by 2x to 5x.",
        "faq3_q": "How fast can Naslogic deliver a dental landing page?",
        "faq3_a": "We deliver production-ready dental landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Every page we build is mobile-first. Over 60% of patients searching for a new dentist do so on their phone.",
        "faq5_a": "Yes. We integrate with popular dental CRMs like NexHealth and RevenueWell.",
        "h1_2": "For Dental",
        "h1_3": "Practices",
        "hook": "Naslogic builds high-converting landing pages exclusively for dental practices. We design pages that turn website visitors into booked appointments for implants, clear aligners, and cosmetic dentistry. No generic templates. Every page is custom-engineered to match your dental market and generate qualified leads on autopilot.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Dental Examples",
        "prob_h2": "Why Most Dental Websites Fail",
        "prob_sub": "Dentists invest in marketing, but their websites let them down. Patients searching for a new dentist need to trust you instantly.",
        "prob1_p": "You get clicks from patients searching for Invisalign or implants, but your site does not give them a clear next step.",
        "prob2_p": "Over 60% of patients search for dentists on their phone. If your site loads slowly, you are losing high-ticket cosmetic leads.",
        "prob3_p": "Template websites make dental practices look like every other clinic in town.",
        "comp_sub": "See why dentists choose a specialist over a one-size-fits-all agency.",
        "comp_1": "Dental industry expertise",
        "comp_1_check": "Built for dental practices",
        "comp_crm": "NexHealth, RevenueWell",
        "port_h2": "Dental Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for dental practices to turn visitors into scheduled appointments.",
        "port_1_img": "Dental LP Preview",
        "port_1_title": "Cosmetic Dentistry & Implants",
        "port_1_t1": "Cosmetic Dentistry",
        "port_1_t2": "High-Ticket",
        "port_1_t3": "Patient Booking",
        "port_2_img": "Orthodontics LP",
        "port_2_title": "Clear Aligner Specialists",
        "port_2_t1": "Orthodontics",
        "port_2_t2": "Invisalign",
        "port_2_t3": "Lead Gen",
        "step_1": "We learn your dental niche — cosmetic, implants, general — and map out your ideal patient journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to dental marketing best practices.",
        "step_3": "Your page goes live and starts converting visitors into booked appointments and new patient consultations.",
        "faq_sub": "Common questions from dentists about our landing page design.",
        "cta_h2": "Ready to Book More High-Ticket Patients?",
        "cta_p": "Stop losing patients to competitors with better websites. Get a landing page that converts dental searches into booked appointments."
    },
    {
        "file": "realestate.html",
        "url": "realestate",
        "title": "Real Estate Landing Pages | Custom Lead Gen Pages | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for real estate agents and wholesalers. Get more seller leads, buyer inquiries, and booked appointments.",
        "og_title": "Real Estate Landing Pages That Book Leads | Naslogic",
        "og_desc": "Custom-built landing pages for realtors. More leads, higher conversions, zero wasted ad spend.",
        "schema_name": "Real Estate Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for real estate agents and wholesalers.",
        "schema_service": "Landing Page Design for Real Estate Professionals",
        "faq1": "Our real estate landing pages start at $199 for a single high-converting page with mobile-first design and SEO optimization.",
        "faq2_q": "Why do realtors need a dedicated landing page?",
        "faq2_a": "Driving traffic to a standard brokerage site leaks leads. A dedicated landing page with a single home valuation or property tour CTA increases conversions by 2x to 5x.",
        "faq3_q": "How fast can Naslogic deliver a real estate landing page?",
        "faq3_a": "We deliver production-ready landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Every page we build is mobile-first. The vast majority of real estate searches happen on mobile devices.",
        "faq5_a": "Yes. We integrate with popular real estate CRMs like Follow Up Boss and Sierra Interactive.",
        "h1_2": "For Real Estate",
        "h1_3": "Professionals",
        "hook": "Naslogic builds high-converting landing pages exclusively for real estate agents and wholesalers. We design pages that turn website visitors into motivated seller leads, buyer appointments, and closed deals. No generic templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Real Estate Examples",
        "prob_h2": "Why Most Real Estate Websites Fail",
        "prob_sub": "Realtors invest in marketing, but generic brokerage websites bleed leads. Buyers and sellers need to trust you instantly.",
        "prob1_p": "You get clicks from motivated sellers, but your site is confusing. They leave without submitting their address.",
        "prob2_p": "If your IDX site loads slowly on mobile, you are losing high-ticket commissions every single day.",
        "prob3_p": "Template websites make you look like every other agent in town. Clients cannot tell you apart from the competition.",
        "comp_sub": "See why top producers choose a specialist over a one-size-fits-all agency.",
        "comp_1": "Real estate industry expertise",
        "comp_1_check": "Built for real estate agents",
        "comp_crm": "Follow Up Boss, Sierra Interactive",
        "port_h2": "Real Estate Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for real estate professionals to turn visitors into leads.",
        "port_1_img": "Real Estate LP Preview",
        "port_1_title": "Motivated Seller Funnel",
        "port_1_t1": "Seller Leads",
        "port_1_t2": "Wholesaling",
        "port_1_t3": "High-Conversion",
        "port_2_img": "Luxury Real Estate LP",
        "port_2_title": "Luxury Listing Page",
        "port_2_t1": "Luxury",
        "port_2_t2": "Buyer Leads",
        "port_2_t3": "Premium Design",
        "step_1": "We learn your real estate niche — luxury buyers, motivated sellers, commercial — and map out the lead journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to real estate marketing.",
        "step_3": "Your page goes live and starts converting visitors into booked listings and buyer appointments.",
        "faq_sub": "Common questions from real estate agents about our landing page design.",
        "cta_h2": "Ready to Close More Deals?",
        "cta_p": "Stop losing leads to competitors. Get a landing page that converts real estate searches into commissions."
    },
    {
        "file": "saas.html",
        "url": "saas",
        "title": "SaaS Landing Pages | Startup Pages That Convert | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for SaaS startups. Get more signups, lower CAC, and better MRR with a page engineered for software.",
        "og_title": "SaaS Landing Pages That Drive MRR | Naslogic",
        "og_desc": "Custom-built landing pages for B2B and B2C SaaS. Higher signups, premium design, lower acquisition costs.",
        "schema_name": "SaaS Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for SaaS startups and tech companies.",
        "schema_service": "Landing Page Design for SaaS Startups",
        "faq1": "Our SaaS landing pages start at $199 for a highly optimized, conversion-ready page.",
        "faq2_q": "Why do SaaS companies need custom landing pages?",
        "faq2_a": "You need to lower your CAC and stand out in a crowded market. A custom SaaS landing page clearly explains the value prop and drives trials 2x to 5x better than generic templates.",
        "faq3_q": "How fast can Naslogic deliver a SaaS landing page?",
        "faq3_a": "Startups move fast and so do we. We deliver production-ready landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Every page is mobile-first, ensuring smooth conversions across all devices.",
        "faq5_a": "Yes. We integrate perfectly with SaaS tools like HubSpot, Segment, Stripe, and Mixpanel.",
        "h1_2": "For SaaS",
        "h1_3": "Startups",
        "hook": "Naslogic builds high-converting landing pages exclusively for SaaS startups. We design pages that turn website visitors into free trials, booked demos, and paying users. No generic templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See SaaS Examples",
        "prob_h2": "Why Most Startup Websites Fail",
        "prob_sub": "Startups spend a fortune on ads and content, but poor messaging and design kills their conversion rates.",
        "prob1_p": "You get clicks from ideal ICPs, but your site is confusing to navigate. They leave without starting a trial.",
        "prob2_p": "Muddled value propositions mean visitors bounce before understanding your software.",
        "prob3_p": "Template websites make your SaaS look like a cheap side-project, not an enterprise-grade solution.",
        "comp_sub": "See why founders choose a specialist over a slow, traditional agency.",
        "comp_1": "SaaS scaling expertise",
        "comp_1_check": "Built for software startups",
        "comp_crm": "HubSpot, Stripe, Mixpanel",
        "port_h2": "SaaS Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for software startups to drive MRR.",
        "port_1_img": "SaaS LP Preview",
        "port_1_title": "B2B AI Software",
        "port_1_t1": "B2B SaaS",
        "port_1_t2": "Enterprise",
        "port_1_t3": "Book Demo",
        "port_2_img": "Consumer SaaS LP",
        "port_2_title": "PLG Consumer App",
        "port_2_t1": "Product-Led Growth",
        "port_2_t2": "Free Trials",
        "port_2_t3": "B2C",
        "step_1": "We learn your product, ICP, and value proposition.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to software marketing.",
        "step_3": "Your page goes live and starts driving signups, decreasing CAC, and growing MRR.",
        "faq_sub": "Common questions from founders about our landing page design.",
        "cta_h2": "Ready to Grow MRR?",
        "cta_p": "Stop burning runway on bad conversions. Get a landing page that turns traffic into active users."
    },
    {
        "file": "ecommerce.html",
        "url": "ecommerce",
        "title": "E-Commerce Landing Pages | Product Drops That Sell Out | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for DTC and E-Commerce. Lower CAC and increase ROAS with a beautifully engineered product page.",
        "og_title": "E-Commerce Landing Pages That Convert | Naslogic",
        "og_desc": "Custom advertorials and product drop landing pages for DTC brands.",
        "schema_name": "E-Commerce Landing Page Design",
        "schema_desc": "Naslogic builds high-converting landing pages specifically for DTC and E-Commerce brands to maximize ROAS.",
        "schema_service": "Landing Page Design for E-Commerce Brands",
        "faq1": "Our e-commerce landing pages start at $199 with conversion-focused layouts for higher AOV.",
        "faq2_q": "Why use a landing page over a standard Shopify product page?",
        "faq2_a": "Driving ad traffic to a standard catalog page results in high bounce rates. A dedicated landing page acts as a sales letter, removing distractions and increasing ROAS significantly.",
        "faq3_q": "How fast can Naslogic deliver an e-commerce page?",
        "faq3_a": "We deliver production-ready landing pages on rapid turnarounds, perfect for upcoming product drops.",
        "faq4_a": "Absolutely. Over 80% of DTC traffic is mobile. Our pages are rigorously tested for mobile checkout flow.",
        "faq5_a": "Yes. We integrate perfectly with Shopify, Klaviyo, and ReCharge.",
        "h1_2": "For E-Commerce",
        "h1_3": "Brands",
        "hook": "Naslogic builds high-converting landing pages exclusively for DTC and E-Commerce brands. We design advertorials and product pages that maximize ROAS, increase AOV, and turn cold traffic into loyal buyers. No generic Shopify templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See E-Commerce Examples",
        "prob_h2": "Why Most DTC Brands Burn Ad Spend",
        "prob_sub": "Brands invest heavily in Meta and TikTok ads, but poor landing page experiences destroy their ROAS.",
        "prob1_p": "You send expensive traffic to a basic product page filled with distractions. They leave without adding to cart.",
        "prob2_p": "If your site loads slowly on mobile, your bounce rate spikes and your advertising dollars go to waste.",
        "prob3_p": "Standard Shopify themes don't tell a persuasive brand story or handle objections effectively.",
        "comp_sub": "See why 8-figure brands choose a specialist over a standard web agency.",
        "comp_1": "DTC conversion expertise",
        "comp_1_check": "Built for e-commerce",
        "comp_crm": "Shopify, Klaviyo, ReCharge",
        "port_h2": "E-Commerce Pages We Have Built",
        "port_sub": "High-ROAS landing pages designed specifically for DTC brands to drive massive sales volume.",
        "port_1_img": "E-Commerce LP Preview",
        "port_1_title": "Supplement Advertorial",
        "port_1_t1": "Health & Wellness",
        "port_1_t2": "Advertorial",
        "port_1_t3": "High AOV",
        "port_2_img": "Fashion Drop LP",
        "port_2_title": "Streetwear Product Drop",
        "port_2_t1": "Apparel",
        "port_2_t2": "Hype Drop",
        "port_2_t3": "Mobile-First",
        "step_1": "We analyze your top-performing creatives, offers, and target demographics.",
        "step_2": "Our team designs and develops a mobile-first, high-converting advertorial or product page.",
        "step_3": "Your page goes live and starts scaling your ROAS and driving profitable acquisitions.",
        "faq_sub": "Common questions from e-commerce founders about our landing page design.",
        "cta_h2": "Ready to Scale Your ROAS?",
        "cta_p": "Stop wasting ad spend on low-converting product pages. Get a custom landing page that actually sells."
    },
    {
        "file": "legal.html",
        "url": "legal",
        "title": "Law Firm Landing Pages | Custom Pages That Book Clients | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for law firms and attorneys. Get more personal injury leads, family law consults, and high-ticket cases.",
        "og_title": "Law Firm Landing Pages That Book Cases | Naslogic",
        "og_desc": "Custom-built landing pages for attorneys. More high-ticket cases, zero wasted ad spend.",
        "schema_name": "Law Firm Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for law firms and attorneys.",
        "schema_service": "Landing Page Design for Attorneys",
        "faq1": "Our legal landing pages start at $199 with mobile-first design and premium aesthetics.",
        "faq2_q": "Why do attorneys need a dedicated landing page?",
        "faq2_a": "Law firms pay incredibly high CPCs on Google. A dedicated landing page ensures that expensive traffic converts by focusing on a specific practice area with a clear CTA.",
        "faq3_q": "How fast can Naslogic deliver a legal landing page?",
        "faq3_a": "We deliver production-ready law firm landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Over 60% of clients searching for an attorney do so on their phone.",
        "faq5_a": "Yes. We integrate with popular legal CRMs like Clio and MyCase.",
        "h1_2": "For Law Firms",
        "h1_3": "& Attorneys",
        "hook": "Naslogic builds high-converting landing pages exclusively for law firms. We design pages that turn website visitors into booked consultations for personal injury, criminal defense, and family law. No generic templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Legal Examples",
        "prob_h2": "Why Most Law Firm Websites Fail",
        "prob_sub": "Attorneys invest in marketing, but their websites let them down. Clients in stressful situations need to trust you instantly.",
        "prob1_p": "You get clicks from clients searching for help, but your site is overwhelming. They leave and call a competitor.",
        "prob2_p": "If your site loads slowly on mobile, you are losing high-ticket cases every single day.",
        "prob3_p": "Template websites make attorneys look unapproachable or untrustworthy.",
        "comp_sub": "See why top law firms choose a specialist over a generic agency.",
        "comp_1": "Legal industry expertise",
        "comp_1_check": "Built for law firms",
        "comp_crm": "Clio, MyCase",
        "port_h2": "Legal Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for attorneys to schedule consultations.",
        "port_1_img": "Legal LP Preview",
        "port_1_title": "Personal Injury Firm",
        "port_1_t1": "Personal Injury",
        "port_1_t2": "High-Ticket",
        "port_1_t3": "Consult Booking",
        "port_2_img": "Family Law LP",
        "port_2_title": "Family Law & Divorce",
        "port_2_t1": "Family Law",
        "port_2_t2": "Lead Gen",
        "port_2_t3": "Trust Building",
        "step_1": "We learn your practice areas and map out the client intake journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to legal marketing.",
        "step_3": "Your page goes live and starts converting visitors into booked consults and retained clients.",
        "faq_sub": "Common questions from attorneys about our landing page design.",
        "cta_h2": "Ready to Book More Cases?",
        "cta_p": "Stop losing high-ticket clients to competitors with better websites. Get a landing page that converts."
    },
    {
        "file": "fitness.html",
        "url": "fitness",
        "title": "Fitness Landing Pages | Custom Pages That Book Clients | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for fitness coaches and gyms. Get more trial members, high-ticket coaching clients, and leads.",
        "og_title": "Fitness Landing Pages That Book Clients | Naslogic",
        "og_desc": "Custom-built landing pages for gyms and fitness coaches. More leads, zero wasted ad spend.",
        "schema_name": "Fitness Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for gyms, fitness studios, and online coaches.",
        "schema_service": "Landing Page Design for Fitness Businesses",
        "faq1": "Our fitness landing pages start at $199 with mobile-first design and premium aesthetics.",
        "faq2_q": "Why do gyms and coaches need a dedicated landing page?",
        "faq2_a": "Driving traffic to a messy homepage leaks leads. A dedicated landing page with a single offer (like a 7-day trial) increases conversion rates by 2x to 5x.",
        "faq3_q": "How fast can Naslogic deliver a fitness landing page?",
        "faq3_a": "We deliver production-ready fitness landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Over 80% of fitness-related searches and social clicks happen on mobile.",
        "faq5_a": "Yes. We integrate with popular gym CRMs like Mindbody and PushPress.",
        "h1_2": "For Fitness",
        "h1_3": "Brands & Gyms",
        "hook": "Naslogic builds high-converting landing pages exclusively for fitness businesses. We design pages that turn website visitors into booked introductory sessions, free trials, and high-ticket coaching clients. No generic templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Fitness Examples",
        "prob_h2": "Why Most Fitness Websites Fail",
        "prob_sub": "Gyms and coaches invest in marketing, but their websites let them down. Prospects need motivation and a clear path to get started.",
        "prob1_p": "You get clicks from ads, but your site does not give them a clear next step. They leave without signing up.",
        "prob2_p": "If your site loads slowly on mobile, you lose impulse buyers from Instagram and Facebook.",
        "prob3_p": "Template websites make your fitness brand look like every other generic gym in town.",
        "comp_sub": "See why fitness entrepreneurs choose a specialist over a one-size-fits-all agency.",
        "comp_1": "Fitness industry expertise",
        "comp_1_check": "Built for gyms & coaches",
        "comp_crm": "Mindbody, PushPress",
        "port_h2": "Fitness Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for fitness businesses to turn visitors into members.",
        "port_1_img": "Fitness LP Preview",
        "port_1_title": "Local Boutique Gym",
        "port_1_t1": "Local Lead Gen",
        "port_1_t2": "Free Trial Offer",
        "port_1_t3": "Studio",
        "port_2_img": "Online Coaching LP",
        "port_2_title": "Online High-Ticket Coach",
        "port_2_t1": "Online Coaching",
        "port_2_t2": "High-Ticket",
        "port_2_t3": "Application Funnel",
        "step_1": "We learn your fitness niche and map out your ideal client journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to fitness marketing.",
        "step_3": "Your page goes live and starts converting visitors into trials, consults, and paying members.",
        "faq_sub": "Common questions from fitness owners about our landing page design.",
        "cta_h2": "Ready to Grow Your Client Base?",
        "cta_p": "Stop losing leads to competitors. Get a landing page that converts fitness searches into passionate members."
    },
    {
        "file": "restaurants.html",
        "url": "restaurants",
        "title": "Restaurant Landing Pages | Custom Pages That Drive Orders | Naslogic",
        "desc": "Naslogic builds high-converting landing pages for restaurants and ghost kitchens. Get more reservations, catering leads, and direct online orders.",
        "og_title": "Restaurant Landing Pages That Drive Orders | Naslogic",
        "og_desc": "Custom-built landing pages for restaurants. More reservations, more direct orders, zero wasted ad spend.",
        "schema_name": "Restaurant Landing Page Design",
        "schema_desc": "Naslogic builds high-converting, mobile-first landing pages specifically for restaurants, ghost kitchens, and catering services.",
        "schema_service": "Landing Page Design for Restaurants",
        "faq1": "Our restaurant landing pages start at $199 with mobile-first design, perfect for hungry locals on the go.",
        "faq2_q": "Why do restaurants need a dedicated landing page?",
        "faq2_a": "To drive specific actions. Whether pushing a new catering menu, private events, or direct orders to avoid 3rd-party app fees, a landing page focuses the customer.",
        "faq3_q": "How fast can Naslogic deliver a restaurant landing page?",
        "faq3_a": "We deliver production-ready restaurant landing pages on rapid turnarounds.",
        "faq4_a": "Absolutely. Nearly 90% of restaurant searches are done on mobile phones. Our pages load instantly to capture hungry customers.",
        "faq5_a": "Yes. We integrate with popular restaurant tech like Toast, SevenRooms, and OpenTable.",
        "h1_2": "For Restaurants",
        "h1_3": "& Ghost Kitchens",
        "hook": "Naslogic builds high-converting landing pages exclusively for the hospitality industry. We design pages that turn website visitors into booked reservations, catering leads, and direct online orders. No generic templates.",
        "cta_1": "Get Your Free Quote",
        "cta_2": "See Restaurant Examples",
        "prob_h2": "Why Most Restaurant Websites Fail",
        "prob_sub": "Restaurants invest in marketing, but poor websites cause hungry customers to bounce to delivery apps.",
        "prob1_p": "Customers can't find your menu or ordering link easily on mobile, so they leave frustrated.",
        "prob2_p": "If your site loads slowly, you lose revenue to competitors or 3rd-party apps that take 30% cuts.",
        "prob3_p": "Template websites fail to capture the atmosphere and crave-ability of your food.",
        "comp_sub": "See why top restaurateurs choose a specialist over a one-size-fits-all agency.",
        "comp_1": "Hospitality industry expertise",
        "comp_1_check": "Built for restaurants",
        "comp_crm": "Toast, OpenTable, SevenRooms",
        "port_h2": "Restaurant Pages We Have Built",
        "port_sub": "Conversion-first landing pages designed specifically for restaurants and catering services.",
        "port_1_img": "Restaurant LP Preview",
        "port_1_title": "Direct Ordering Promo",
        "port_1_t1": "Ghost Kitchen",
        "port_1_t2": "Direct Orders",
        "port_1_t3": "High-Conversion",
        "port_2_img": "Catering LP",
        "port_2_title": "Corporate Catering Leads",
        "port_2_t1": "Catering",
        "port_2_t2": "B2B Leads",
        "port_2_t3": "Event Booking",
        "step_1": "We learn your restaurant concept, menu goals, and map out the customer journey.",
        "step_2": "Our team designs and develops a mobile-first, conversion-optimized landing page tailored to hospitality marketing.",
        "step_3": "Your page goes live and starts converting visitors into reservations, catering leads, and direct orders.",
        "faq_sub": "Common questions from restaurant owners about our landing page design.",
        "cta_h2": "Ready to Drive More Direct Revenue?",
        "cta_p": "Stop losing 30% to delivery apps simply because your website is hard to use. Get a landing page that converts."
    }
]

with open("roofing.html", "r", encoding="utf-8") as f:
    template = f.read()

for niche in niches:
    content = template
    
    content = content.replace("Roofing Landing Pages | Custom Pages That Book Estimates | Naslogic", niche["title"])
    content = content.replace("Naslogic builds high-converting landing pages for roofing contractors. Get more shingle replacement leads, storm damage calls, and booked estimates with a page engineered for your market.", niche["desc"])
    content = content.replace("https://naslogic.com/roofing", f"https://naslogic.com/{niche['url']}")
    content = content.replace("Roofing Landing Pages That Book Estimates | Naslogic", niche["og_title"])
    content = content.replace("Custom-built landing pages for roofing contractors. More leads, more booked estimates, zero wasted ad spend.", niche["og_desc"])
    
    content = content.replace('"Roofing Landing Page Design"', f'"{niche["schema_name"]}"')
    content = content.replace('"Naslogic builds high-converting, mobile-first landing pages specifically for roofing contractors. Our pages are designed to convert visitors into booked estimates for services like shingle replacement, storm damage repair, and roof inspections."', f'"{niche["schema_desc"]}"')
    content = content.replace('"Landing Page Design for Roofing Contractors"', f'"{niche["schema_service"]}"')
    
    content = content.replace("Naslogic's roofing landing pages start at $199 for a single high-converting page with mobile-first design, SEO optimization, and conversion-focused layouts. Multi-page funnels and custom integrations are priced on a project basis.", niche["faq1"])
    content = content.replace("Why do roofing contractors need a dedicated landing page?", niche["faq2_q"])
    content = content.replace("Roofing contractors spend significant budgets driving traffic, but most send visitors to generic homepages. A dedicated landing page with a single call-to-action, trust signals, and a streamlined estimate booking flow can increase conversion rates by 2x to 5x compared to a standard website.", niche["faq2_a"])
    
    content = content.replace("How fast can Naslogic deliver a roofing landing page?", niche["faq3_q"])
    content = content.replace("We deliver production-ready roofing landing pages on rapid turnarounds. Most single-page projects are completed within days, not the weeks or months typical of traditional agencies.", niche["faq3_a"])
    
    content = content.replace("Absolutely. Every page we build is mobile-first. Over 60% of homeowners searching for roofing services do so on their phone. Our pages are engineered to load fast, look flawless, and convert on any screen size.", niche["faq4_a"])
    content = content.replace("Yes. We integrate with popular roofing CRMs like JobNimbus, AccuLynx, and Roofr, as well as general tools like HubSpot, Calendly, and Google Sheets. Lead data flows directly into your existing workflow.", niche["faq5_a"])
    
    content = content.replace("<span>For Roofing</span>", f"<span>{niche['h1_2']}</span>")
    content = content.replace("<span>Contractors</span>", f"<span>{niche['h1_3']}</span>")
    
    content = content.replace("Naslogic builds high-converting landing pages exclusively for roofing contractors. We design pages that turn website visitors into booked estimates for shingle replacement, storm damage repair, and full re-roofs. No generic templates. Every page is custom-engineered to match your roofing market and generate qualified leads on autopilot.", niche["hook"])
    
    content = content.replace("Get Your Free Quote", niche["cta_1"])
    content = content.replace("See Roofing Examples", niche["cta_2"])
    
    content = content.replace("Why Most Roofing Websites Fail", niche["prob_h2"])
    content = content.replace("Roofing contractors invest in marketing, but their websites let them down. Homeowners searching for roof repair, shingle replacement, or storm damage restoration need to trust you instantly — or they bounce to the next contractor.", niche["prob_sub"])
    
    content = content.replace("You get clicks from homeowners searching for roof leak repair and free inspections, but your site does not give them a clear next step. They leave without ever calling you.", niche["prob1_p"])
    content = content.replace("Over 65% of homeowners search for roofing contractors on their phone. If your site loads slowly or looks broken on mobile, you are losing shingle replacement leads every single day.", niche["prob2_p"])
    content = content.replace("Template websites make roofing companies look like every other contractor in town. Homeowners cannot tell you apart from the competition when everyone has the same layout.", niche["prob3_p"])
    
    content = content.replace("See why roofing contractors choose a specialist over a one-size-fits-all agency when it comes to lead generation and contractor marketing.", niche["comp_sub"])
    content = content.replace("Roofing industry expertise", niche["comp_1"])
    content = content.replace("Built for roofing contractors", niche["comp_1_check"])
    content = content.replace("JobNimbus, AccuLynx, Roofr", niche["comp_crm"])
    
    content = content.replace("Roofing Pages We Have Built", niche["port_h2"])
    content = content.replace("Conversion-first landing pages designed specifically for roofing companies to turn visitors into scheduled estimates and signed contracts.", niche["port_sub"])
    
    content = content.replace("Roofing LP Preview", niche["port_1_img"])
    content = content.replace("Storm Damage Specialists", niche["port_1_title"])
    content = content.replace("Residential Roofing", niche["port_1_t1"])
    content = content.replace("Lead Gen", niche["port_1_t2"])
    content = content.replace("Estimate Booking", niche["port_1_t3"])
    
    content = content.replace("Commercial Roofing LP", niche["port_2_img"])
    content = content.replace("Commercial Flat Roof Pros", niche["port_2_title"])
    content = content.replace("Commercial", niche["port_2_t1"])
    content = content.replace("TPO & EPDM", niche["port_2_t2"])
    content = content.replace("B2B Leads", niche["port_2_t3"])
    
    content = content.replace("We learn your roofing niche — residential re-roofs, storm damage, commercial flat roofing — and map out your ideal customer journey.", niche["step_1"])
    content = content.replace("Our team designs and develops a mobile-first, conversion-optimized landing page tailored to roofing contractor marketing best practices.", niche["step_2"])
    content = content.replace("Your page goes live and starts converting visitors into booked roof inspections, free estimates, and signed contracts on autopilot.", niche["step_3"])
    
    content = content.replace("Common questions from roofing contractors about our landing page design and lead generation services.", niche["faq_sub"])
    
    content = content.replace("Ready to Book More Roofing Jobs?", niche["cta_h2"])
    content = content.replace("Stop losing homeowners to competitors with better websites. Get a landing page that converts roof inspections into signed contracts.", niche["cta_p"])
    
    with open(niche["file"], "w", encoding="utf-8") as out:
        out.write(content)
        
    print(f"Generated {niche['file']}")
