
export const siteConfig = {
    name: "Naslogic — Fort Myers Web Design & Landing Page Agency",
    description: "Custom-built landing pages & websites designed and delivered in 48 hours for $199. Fort Myers, FL.",
    url: "https://naslogic.com",
    ogImage: "https://naslogic.com/og.jpg",
    contact: {
        phone: "(941) 257-3059",
        location: "Fort Myers, FL",
    },
    pricing: [
        {
            name: "The Start",
            description: "One perfect page. Built by hand to get you phone calls.",
            price: "$399",
            hostingFee: "+ $29/mo Worry-Free Hosting",
            features: [
                "1 Custom Built Landing Page",
                "High-Converting Page Psychology",
                "We Write All The Words",
                "Working Contact Forms",
                "Premium Mobile Optimization",
                "Basic Google Setup (SEO)",
                "Fast Loading Speed Guarantee",
                "Premium Stock Photos Included",
                "1 Round of Revisions",
                "Ready in 48 Hours",
            ],
            cta: "Start Growing Today",
        },
        {
            name: "The Growth",
            description: "Up to 5 pages. For businesses ready to look like the best in town.",
            price: "$999",
            hostingFee: "+ $29/mo Worry-Free Hosting",
            features: [
                "Up to 5 Pages",
                "1-on-1 Planning Call",
                "Connect to your CRM/Email",
                "2 Rounds of Revisions",
                "Includes Everything in 'The Start'",
            ],
            cta: "Get Free Quote",
            popular: true,
        },
        {
            name: "The Takeover",
            description: "A complete website build where we do all the heavy lifting.",
            price: "$2,500",
            hostingFee: "+ $49/mo Worry-Free Hosting",
            features: [
                "Up to 10 Pages",
                "Deep Dive Strategy Call",
                "Unlimited Rounds of Revisions",
                "Priority Support Access",
                "Includes Everything in 'The Growth'",
            ],
            cta: "Get Free Quote",
        },
    ],
};
